myWebApp/myWebApp/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Configuration;
using MySql.Data.MySqlClient;
using myWebApp.Models;

namespace myWebApp.Controllers
{
    public class MemberController : Controller
    {
        public ActionResult Home()
        {
            if (Session["user"] != null)
            {
                if (Session["userLevel"].ToString() == "0")
                {
                    return RedirectToAction("Home", "Admin");
                }
                else if (Session["userLevel"].ToString() == "1")
                {
                    return RedirectToAction("Home", "Manager");
                }
                else
                //Session["userLevel"].ToString() == "2"
                {
                    return RedirectToAction("Home", "Employee");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult PasswordChange()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PasswordChange(string newPassword)
        {
            string query,constr;
            int res;

            constr = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;

            query = "UPDATE administrator SET password = '" + newPassword + "' WHERE userName='" + Session["user"].ToString() + "'";
            using (MySqlConnection con = new MySqlConnection(constr))
            {
                using (MySqlCommand cmd = new MySqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    res = cmd.ExecuteNonQuery();
                    con.Close();
                }
            }

            query = "UPDATE employee SET accountPassword = '" + newPassword + "' WHERE id=" + Session["user"].ToString();
            using (MySqlConnection con = new MySqlConnection(constr))
            {
                using (MySqlCommand cmd = new MySqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    res = cmd.ExecuteNonQuery();
                    con.Close();
                }
            }
            return Home();
        }

        public ActionResult LogOut()
        {
            Session.Remove("user");
            Session.Remove("userName");
            Session.Remove("userLevel");
            return RedirectToAction("Index", "Home");
        }
        
        public ActionResult EmployeeList()
        {
            User us = new User();
            
            if (Session["user"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
                string query, constr;
            List<User> userList = new List<User>();
            //----------------------
            myappEntities md = new myappEntities();
            var employeeList = from c in md.employee
                               orderby c.name
                               select new { c.id, c.name };
            foreach(var usr in employeeList)
            {
                userList.Add(new User
                {
                    Id = usr.id.ToString(),
                    Name = usr.name
                });
            }
            

            //----------------------------
            /*
            constr = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
            if (Session["userLevel"].ToString() == "0" || Session["userLevel"].ToString() == "1")
            {
                if (Session["userLevel"].ToString() == "0")
                {
                    query = "SELECT id, name FROM employee WHERE accountLevel<>'0'";
                }
                else
                {
                    query = "SELECT employee.id, employee.name FROM management INNER JOIN employee ON management.employeeID = employee.id WHERE management.managerID='" + Session["user"] + "'";
                }
                using (MySqlConnection con = new MySqlConnection(constr))
                {
                    using (MySqlCommand cmd = new MySqlCommand(query))
                    {
                        cmd.Connection = con;
                        con.Open();
                        using (MySqlDataReader sdr = cmd.ExecuteReader())
                        {
                            while (sdr.Read())
                            {
                                userList.Add(new User
                                {
                                    Id = sdr["id"].ToString(),
                                    Name = sdr["name"].ToString()
                                });
                            }
                        }
                        con.Close();
                    }
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }*/
            return View(userList);
        }

        public ActionResult Timekeeping()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public ActionResult TimekeepingInfo()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            string constr, query, timeSearch;
            timeSearch = DateTime.Now.ToString("MM/yyyy");
            if (Session["userLevel"].ToString() == "0")
            {
                return RedirectToAction("TimekeepingListOfMember");
                //query = "SELECT * FROM timekeeping WHERE date LIKE '%/" + timeSearch + "'";
            }
            else
                //Session["userLevel"].ToString() == "1" || Session["userLevel"].ToString() == "2"
            {
                query = "SELECT * FROM timekeeping WHERE employeeID = '" + Session["user"] + "' AND date LIKE '%/" + timeSearch + "'";
            }
    
            List<Timekeeping> timekeepingList = new List<Timekeeping>();
            constr = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;          
            
            using (MySqlConnection conn = new MySqlConnection(constr))
            {
                using (MySqlCommand cmd = new MySqlCommand(query))
                {
                    cmd.Connection = conn;
                    conn.Open();
                    using (MySqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while(sdr.Read())
                        {
                            timekeepingList.Add(new Timekeeping
                            {
                                EmployeeID = sdr["employeeID"].ToString(),
                                Date = sdr["date"].ToString(),
                                TimeIn = sdr["timeIn"].ToString(),
                                TimeOut = sdr["timeOut"].ToString()
                            });
                        }
                    }
                    conn.Close();
                }
            }
            ViewBag.timeKeeping = "personal";
            return View("TimekeepingList", timekeepingList);
        }
        
        public ActionResult TimekeepingListOfMember()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            string constr, query, timeSearch, employeeID="";
            timeSearch = DateTime.Now.ToString("MM/yyyy");

            constr = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
            List<User> user_1 = new List<User>();
            MySqlDataReader sdr;
            MySqlCommand cmd;
            string userInfo;
            List<string> user_2 = new List<string>();
            List<Timekeeping> timekeepingList = new List<Timekeeping>();

            using (MySqlConnection conn = new MySqlConnection(constr))
            {
                conn.Open();
                query = "SELECT employee.id, employee.name FROM management INNER JOIN employee ON management.employeeID = employee.id WHERE management.managerID='" + Session["user"] + "'";
                using (cmd = new MySqlCommand(query, conn))
                {
                    sdr = cmd.ExecuteReader();
                    while (sdr.Read())
                    {
                        user_1.Add(new User {
                            Id = sdr["id"].ToString(),
                            Name = sdr["name"].ToString()
                        });
                    }  
                }
                conn.Close();
                if(user_1.Count > 0)
                {
                    foreach (User eachUser in user_1)
                    {
                        conn.Open();
                        if (employeeID == "")
                        {
                            employeeID = eachUser.Id;
                        }
                        query = "SELECT employee.id, employee.name FROM management INNER JOIN employee ON management.employeeID = employee.id WHERE management.managerID='" + eachUser.Id + "'";
                        userInfo = eachUser.Id + "-" + eachUser.Name;
                        user_2.Add(userInfo);
                        using (cmd = new MySqlCommand(query, conn))
                        {
                            sdr = cmd.ExecuteReader();
                            while(sdr.Read())
                            {
                                userInfo = sdr["id"].ToString() + "-" + sdr["name"].ToString();
                                user_2.Add(userInfo);
                            }
                        }
                        conn.Close();
                    }  
                }

myWebApp/myWebApp/Controllers/api/TimekeepingController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;

namespace myWebApp.Controllers
{
    public class TimekeepingController : ApiController
    {
        [System.Web.Http.HttpGet]
        public IHttpActionResult GetTimekeepingbyEmployeeId(int employeeID)
        {
            IList<timekeeping> timekeepingList;
            using (var myappEntiObj = new myappEntities())
            {
                timekeepingList = myappEntiObj.timekeeping.Select(t => new timekeeping()
                {
                    date = t.date,
                    timeIn = t.timeIn,
                    timeOut = t.timeOut
                }).ToList<timekeeping>();
            }
            
            /*------------------------------------------------------------------
            IList<timekeeping> timekeepingList = new List<timekeeping>();
            using (var md = new myappEntities())
            {
                var timekeepingRes = from c in md.timekeeping
                                     where c.employeeID == employeeID
                                     orderby c.date descending
                                     select new { c.employeeID, c.date, c.timeIn, c.timeOut };
                foreach (var item in timekeepingRes)
                {
                    timekeepingList.Add(new timekeeping()
                    {
                        date = item.date,
                        timeIn = item.timeIn,
                        timeOut = item.timeOut
                    });
                }
            }-----------------------------------------------------------------*/

            if(timekeepingList.Count == 0)
            {
                return NotFound();
            }
            return Ok(timekeepingList);     
        }
        
        [System.Web.Http.HttpPost]
        public IHttpActionResult TakeTimekeeping(timekeeping checkTimeInfo)
        {
            if(!ModelState.IsValid)
            {
                return BadRequest();
            }
            using (var myappEntiObj = new myappEntities())
            {
                myappEntiObj.timekeeping.Add(new timekeeping()
                {
                    employeeID = checkTimeInfo.employeeID,
                    timeIn = checkTimeInfo.timeIn,
                    timeOut = checkTimeInfo.timeOut,
                    date = checkTimeInfo.date,
                    createdBy = checkTimeInfo.createdBy,
                    modifiedBy = checkTimeInfo.modifiedBy
                });
                myappEntiObj.SaveChanges();
            }
            return Ok();
        }
        /*
        [System.Web.Http.HttpGet]
        public IHttpActionResult GetEmployeeById(int employeeID)
        {
            List<employee> emloyeeInfo = new List<employee>();
            myappEntities md = new myappEntities();
            var employeeRes = from c in md.employee
                                 where c.id == employeeID
                                 select new { c.id, c.name };
            /*
            foreach (var item in timekeepingRes)
            {
                timekeepingList.Add(new timekeeping
                {
                    employeeID = item.employeeID,
                    date = item.date,
                    timeIn = item.timeIn,
                    timeOut = item.timeOut
                });
            }*/
            /*return Ok(employeeRes.FirstOrDefault());
        }

        // GET api/values/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/values
        public void Post([FromBody]string value)
        {
        }

        // PUT api/values/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/values/5
        public void Delete(int id)
        {
        }*/
    }
}

myWebApp/myWebApp/Views/Shared/_Layout - Member.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My WebApp</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My WebApp", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @{
                        if (Session["userLevel"].ToString() == "0")
                        {
                            <li>@Html.ActionLink("Trang chủ", "Home", "Member")</li>
                            <li>@Html.ActionLink("Danh sách nhân viên", "EmployeeList", "Member")</li>
                            <li>@Html.ActionLink("Thông tin chấm công", "TimekeepingInfo", "Member")</li>
                            <li>@Html.ActionLink("Phân quyền quản trị", "GrantAdmin", "Member")</li>
                            <li>@Html.ActionLink("Đổi MK", "PasswordChange", "Member")</li>
                            <li>@Html.ActionLink("Thoát TK", "LogOut", "Member")</li>
                        }
                        else if (Session["userLevel"].ToString() == "1")
                        {
                            <li>@Html.ActionLink("Trang chủ", "Home", "Member")</li>
                            <li>@Html.ActionLink("Danh sách nhân viên", "EmployeeList", "Member")</li>
                            <li>@Html.ActionLink("Chấm công", "Timekeeping", "Member")</li>
                            <li>@Html.ActionLink("Thông tin chấm công", "TimekeepingInfo", "Member")</li>
                            <li>@Html.ActionLink("Đổi MK", "PasswordChange", "Member")</li>
                            <li>@Html.ActionLink("Thoát TK", "LogOut", "Member")</li>
                        }
                        else if (Session["userLevel"].ToString() == "2")
                        {
                            <li>@Html.ActionLink("Trang chủ", "Home", "Member")</li>
                            <li>@Html.ActionLink("Chấm công", "Timekeeping", "Member")</li>
                            <li>@Html.ActionLink("Thông tin chấm công", "TimekeepingInfo", "Member")</li>
                            <li>@Html.ActionLink("Đổi MK", "PasswordChange", "Member")</li>
                            <li>@Html.ActionLink("Thoát TK", "LogOut", "Member")</li>
                        }
                    }

                </ul>
                @{
                    if (Session["userName"] == null)
                    {
                        <span class="navbar-text text-white">@Session["user"]</span>
                    }
                    else
                    {
                        <span class="navbar-text text-white">@Session["user"] - @Session["userName"]</span>
                    }
                }

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Chấm công Online</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/myScript")
    @RenderSection("scripts", required: false)
</body>
</html>

myWebApp/myWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Chấm công Online</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/myCSS")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Timekeeping", "Home", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Trang chủ", "Home", "Home")</li>
                    <li>@Html.ActionLink("Giới thiệu", "ProgramInfo", "Home")</li>
                    <li>@Html.ActionLink("Đăng nhập", "Login", "Home")</li>
                    <li>@Html.ActionLink("Đăng nhập quản trị", "ADLogin", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Chấm công Online</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/myScript")
    @RenderSection("scripts", required: false)
</body>
</html>